services:
  point-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/point-service:latest
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:3306/point_db
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}