services:
  point-service:
    image: 267837905230.dkr.ecr.ap-northeast-2.amazonaws.com/board-system/point-service:latest
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
